CREATE VIEW CSE532.ZIPOP(ZIP, ZPOP) AS SELECT DISTINCT ZIP, ZPOP FROM CSE532.ZIPPOP
WHERE ZPOP!=0;

CREATE VIEW CSE532.ZIP_US(ZIP, POP, shape, AVG_POP) AS SELECT  ZIP, ZPOP, shape, ZPOP/db2gse.ST_Area(Shape) 
FROM CSE532.ZIPop JOIN CSE532.USZIP 
ON cse532.ZIPOP.ZIP = cse532.USZIP .ZCTA5CE10 ;

SELECT zu.ZIP, zuu.ZIP, db2gse.ST_Union(zu.SHAPE, zuu.SHAPE) 
FROM CSE532.ZIP_US zu, CSE532.ZIP_US zuu WHERE db2gse.ST_Intersects(zu.SHAPE, zuu.SHAPE) =1
AND zu.ZIP !=zuu.ZIP ;


