CREATE VIEW CSE532.ZIPS(ZIPS) AS 
SELECT DISTINCT
CASE 
    WHEN LOCATE('-',ZIPCODE)=0 THEN ZIPCODE  
    ELSE  SUBSTR(ZIPCODE, 1,LOCATE('-',ZIPCODE)-1)
    END AS ZIPS
FROM CSE532.FACILITY;

CREATE VIEW CSE532.ZIP_ER(ZIPS_ER) AS
SELECT DISTINCT ZIPCODE FROM CSE532.FACILITY  
JOIN  CSE532.FACILITYCERTIFICATION 
ON CSE532.FACILITY.FACILITYID = CSE532.FACILITYCERTIFICATION.FACILITYID 
WHERE ATTRIBUTEVALUE = 'Emergency Department' ;

CREATE VIEW CSE532.ZIP_WO_ER(ZIPS) AS 
SELECT DISTINCT ZIPS
FROM CSE532.ZIPS WHERE ZIPS NOT IN (SELECT ZIPS_ER FROM CSE532.ZIP_ER);

CREATE VIEW CSE532.ZIP_ER_SHAPE(ZIP_ER, SHAPE) AS 
SELECT ZCTA5CE10, SHAPE  FROM CSE532.USZIP INNER JOIN CSE532.ZIP_ER 
ON CSE532.USZIP.ZCTA5CE10 = CSE532.ZIP_ER.ZIPS_ER;


CREATE VIEW CSE532.ZIP_WOER_SHAPE(ZIP_WOER, SHAPE) AS 
SELECT ZCTA5CE10, SHAPE  FROM CSE532.USZIP INNER JOIN CSE532.ZIP_WO_ER 
ON CSE532.USZIP.ZCTA5CE10 = CSE532.ZIP_WO_ER.ZIPS;

CREATE VIEW CSE532.ZIP_WOER_N(ZIP1, ZIP2) AS 
SELECT a.ZIP_WOER , b.ZIP_WOER
FROM CSE532.ZIP_WOER_SHAPE a, CSE532.ZIP_WOER_SHAPE b 
WHERE db2gse.st_intersects(a.Shape, b.Shape) = 1;

CREATE VIEW CSE532.ZIP_WOER_ER_N(ZIP_WOER, ZIP_ER) AS 
SELECT a.ZIP_WOER , b.ZIP_ER
FROM CSE532.ZIP_WOER_SHAPE a, CSE532.ZIP_ER_SHAPE b 
WHERE db2gse.st_intersects(a.Shape, b.Shape) = 1;

SELECT DISTINCT ZIP1 FROM CSE532.ZIP_WOER_N 
WHERE ZIP1 NOT IN (SELECT DISTINCT ZIP_WOER FROM CSE532.ZIP_WOER_ER_N);
