
WITH DEA_MONTH (TRANSACTION_MONTH, TRANSACTION_YEAR, DOSE, YEARDATE ) AS (SELECT MONTH(TRANSACTION_DATE) , YEAR(TRANSACTION_DATE) ,  DOSAGE_UNIT , YEAR(TRANSACTION_DATE)||CASE 
    WHEN (  CAST( MONTH(TRANSACTION_DATE) AS INT)  < 10 ) 
         THEN '0'  || CAST( MONTH(TRANSACTION_DATE) AS INT)
    ELSE CAST ( MONTH(TRANSACTION_DATE) AS CHAR(2) )
END FROM CSE532.DEA_NY )
SELECT  YEARDATE, SUM(DOSE) AS MONTHLY_COUNT , AVG(SUM(DOSE)) OVER (ORDER BY YEARDATE ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING ) AS SMOOTH_COUNT FROM DEA_MONTH GROUP BY YEARDATE;