CREATE VIEW CSE532.ZIP_UNIQUE (ZIP, POP)
AS 
SELECT DISTINCT ZIP, ZPOP FROM CSE532.ZIPPOP;

CREATE VIEW CSE532.DEA_MME (ZIP, SUM_MME)
AS 
SELECT BUYER_ZIP, SUM(MME) FROM CSE532.DEA_NY GROUP BY  BUYER_ZIP;

CREATE VIEW CSE532.MME_POP(ZIP, NORM_MME)
AS 
WITH ZIP_MME(ZIP, POP, MME) AS (SELECT CSE532.ZIP_UNIQUE.ZIP, CSE532.ZIP_UNIQUE.POP, CSE532.DEA_MME.SUM_MME FROM CSE532.ZIP_UNIQUE JOIN CSE532.DEA_MME ON CSE532.ZIP_UNIQUE.ZIP = CSE532.DEA_MME.ZIP WHERE CSE532.ZIP_UNIQUE.POP >0)
SELECT ZIP, MME/POP FROM ZIP_MME;

SELECT ZIP, NORM_MME, RANK() OVER (ORDER BY NORM_MME DESC) AS RANK_ZIP FROM MME_POP LIMIT 5;